### ISSUE TITLE
TODO for weekly work

### ISSUE THREAD

**Issue by annecori** [mrc-ide/EpiEstim#147]
- [ ] add a "details" and "examples" sections
- [ ] in estimate_R_agg Add check (i.e. an error using stop ("useful error msg") f following is not true) that dt is in correct format - probably integer, meaning 7L by default rather than 7
- [ ] in estimate_R_agg Add check that dt_out in is correct format
- [ ] in estimate_R_agg Add check that the grid is a list of 3 elements, all of them numbers, min < max, precision < max - min
- [ ] add a test to check that if incid is not a vector you can't run with dt > 1 (if it's an incidence object or a matrix / dataframe)
- [ ] add a test to check that if method is not parametric or non_parametric you can't run with dt > 1
- [ ] add a test to check that if you don't supply the right arguments it does not work (e.g. no mean_SI for a parametric method)
- [ ] add tests showing that the method work well with a different dt (e.g. 3, 10)
- [ ] add a test that we can plot the output of the R calculated from coarse data using plot(R) - don't check the plot output but check that it can be generated with no error
- [ ] do we want to force I = 1 on the first day; if not then could change the tests in test-weekly to start comparing I on first week
- [ ] do we want to keep the iteration number printed
- [ ] allow user defined tstart and tend?
- [ ] in get_r_from_R inside estimate_R_agg, call things si rather than gt
- [ ] in get_r_from_R could use internal function discs_si rather than rely on discrete

**Comment by annecori** [comment]
@rebeccanash  I think this stems from your work on aggregated incidence. Could you please review especially the unticked boxes and address / close as appropriate? Of course happy to chat if helpful
